server:
  port: 601
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:3000/eureka #eureka服务端提供的注册地址 参考服务端配置的这个路径
#        defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    instance-id: power-1 #此实例注册到eureka服务端的唯一的实例ID--(考虑到 power服务的 集群)
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: server-power
    #此实例注册到eureka服务端的name(注意此name:server-power 是我们逻辑上的，
#      其实对于注册中心eureka 来说都是 客户端 client)